apiVersion: v1
kind: Secret
metadata:
  name: licitaciones-db-secret
  namespace: licitaciones
type: Opaque
stringData:
  POSTGRES_USER: reemplazar-usuario
  POSTGRES_PASSWORD: reemplazar-password
  CONNECTION_STRING: Host=postgres;Port=5432;Database=licitaciones;Username=reemplazar-usuario;Password=reemplazar-password
