apiVersion: v1
kind: ConfigMap
metadata:
  name: licitaciones-config
  namespace: licitaciones
data:
  ASPNETCORE_ENVIRONMENT: Production
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: licitaciones
