apiVersion: v1
kind: Service
metadata:
  name: licitaciones-web
  namespace: licitaciones
spec:
  selector: {app: licitaciones-web}
  type: ClusterIP
  ports: [{name: http, port: 8080, targetPort: 8080}]
