using Licitaciones.Application.Licitaciones;
using Licitaciones.Application.Ofertas;
using Licitaciones.Application.Proveedores;
using Licitaciones.Domain.Licitaciones;
using Licitaciones.Domain.Ofertas;
using Licitaciones.Domain.Proveedores;

namespace Licitaciones.UnitTests.Application.Crud;

public sealed class GestionarCrudTests
{
    [Fact] public async Task Licitaciones_ListarYConsultar() { var l = CrearLicitacion(); var r = new LR(l); var s = new GestionarLicitacionesService(r, new OR()); Assert.Single(await s.ListarAsync()); Assert.Equal(l.Id, (await s.ObtenerAsync(l.Id)).Id); }
    [Fact] public async Task Licitacion_EditarCorrectamente() { var l = CrearLicitacion(); var r = new LR(l); await new GestionarLicitacionesService(r, new OR()).EditarAsync(l.Id, "NUEVO", "Nuevo título", 900m, DateTimeOffset.UtcNow.AddDays(2)); Assert.Equal("NUEVO", l.Codigo); Assert.Equal(900m, l.PresupuestoEstimadoCrc); }
    [Fact] public async Task Licitacion_RechazaPresupuestoMenorQueOferta() { var l = CrearLicitacion(); var o = new OR(new Oferta(l.Id, Guid.NewGuid(), 800m, DateTimeOffset.UtcNow)); await Assert.ThrowsAsync<ArgumentException>(() => new GestionarLicitacionesService(new LR(l), o).EditarAsync(l.Id, l.Codigo, l.Titulo, 700m, l.FechaCierre)); }
    [Fact] public async Task Licitacion_EliminaSinOfertas() { var l = CrearLicitacion(); var r = new LR(l); await new GestionarLicitacionesService(r, new OR()).EliminarAsync(l.Id); Assert.Empty(r.Items); }
    [Fact] public async Task Licitacion_RechazaEliminarConOfertas() { var l = CrearLicitacion(); var o = new OR(new Oferta(l.Id, Guid.NewGuid(), 1m, DateTimeOffset.UtcNow)); await Assert.ThrowsAsync<InvalidOperationException>(() => new GestionarLicitacionesService(new LR(l), o).EliminarAsync(l.Id)); }
    [Fact] public async Task Proveedores_ListarYConsultar() { var p = new Proveedor("Proveedor A"); var r = new PR(p); var s = new GestionarProveedoresService(r, new OR()); Assert.Single(await s.ListarAsync()); Assert.Equal(p.Id, (await s.ObtenerAsync(p.Id)).Id); }
    [Fact] public async Task Proveedor_EditarUsaUpdateYConservaIdentidad() { var creado = DateTimeOffset.UtcNow.AddDays(-1); var p = new Proveedor("Proveedor A", creado); var r = new PR(p); await new GestionarProveedoresService(r, new OR()).EditarAsync(p.Id, "Proveedor B"); Assert.Equal("Proveedor B", p.Nombre); Assert.Equal(creado, p.CreatedAt); Assert.Equal(1, r.GuardarCalls); Assert.Equal(0, r.AgregarCalls); }
    [Fact] public async Task Proveedor_EliminaSinOfertas() { var p = new Proveedor("Proveedor A"); var r = new PR(p); await new GestionarProveedoresService(r, new OR()).EliminarAsync(p.Id); Assert.Empty(r.Items); }
    [Fact] public async Task Proveedor_RechazaEliminarConOfertas() { var p = new Proveedor("Proveedor A"); var o = new OR(new Oferta(Guid.NewGuid(), p.Id, 1m, DateTimeOffset.UtcNow)); await Assert.ThrowsAsync<InvalidOperationException>(() => new GestionarProveedoresService(new PR(p), o).EliminarAsync(p.Id)); }
    private static Licitacion CrearLicitacion() => new("L-CRUD", "Licitación", 1000m, DateTimeOffset.UtcNow.AddDays(1));
    private sealed class LR(Licitacion l) : ILicitacionRepository { public List<Licitacion> Items = [l]; public Task<bool> ExisteConCodigoNormalizadoAsync(string c, CancellationToken t = default) => Task.FromResult(Items.Any(x => x.CodigoNormalizado == c)); public Task AgregarAsync(Licitacion x, CancellationToken t = default) { Items.Add(x); return Task.CompletedTask; } public Task<Licitacion?> ObtenerPorIdAsync(Guid id, CancellationToken t = default) => Task.FromResult(Items.SingleOrDefault(x => x.Id == id)); public Task GuardarCambiosAsync(Licitacion x, CancellationToken t = default) => Task.CompletedTask; public Task<IReadOnlyList<Licitacion>> ListarAsync(CancellationToken t = default) => Task.FromResult<IReadOnlyList<Licitacion>>(Items); public Task EliminarAsync(Licitacion x, CancellationToken t = default) { Items.Remove(x); return Task.CompletedTask; } }
    private sealed class PR(Proveedor p) : IProveedorRepository { public List<Proveedor> Items = [p]; public int AgregarCalls { get; private set; } public int GuardarCalls { get; private set; } public Task<Proveedor?> ObtenerPorIdAsync(Guid id, CancellationToken t = default) => Task.FromResult(Items.SingleOrDefault(x => x.Id == id)); public Task<bool> ExisteConNombreNormalizadoAsync(string n, CancellationToken t = default) => Task.FromResult(Items.Any(x => x.NombreNormalizado == n)); public Task AgregarAsync(Proveedor x, CancellationToken t = default) { AgregarCalls++; return Task.CompletedTask; } public Task GuardarCambiosAsync(Proveedor x, CancellationToken t = default) { GuardarCalls++; return Task.CompletedTask; } public Task<IReadOnlyList<Proveedor>> ListarAsync(CancellationToken t = default) => Task.FromResult<IReadOnlyList<Proveedor>>(Items); public Task EliminarAsync(Proveedor x, CancellationToken t = default) { Items.Remove(x); return Task.CompletedTask; } }
    private sealed class OR(params Oferta[] values) : IOfertaRepository { public List<Oferta> Items = [.. values]; public Task AgregarAsync(Oferta x, CancellationToken t = default) { Items.Add(x); return Task.CompletedTask; } public Task<Oferta?> ObtenerAsync(Guid id, CancellationToken t = default) => Task.FromResult(Items.SingleOrDefault(x => x.Id == id)); public Task<IReadOnlyList<Oferta>> ListarAsync(Guid? l, Guid? p, CancellationToken t = default) => Task.FromResult<IReadOnlyList<Oferta>>(Items.Where(x => (!l.HasValue || x.LicitacionId == l) && (!p.HasValue || x.ProveedorId == p)).ToList()); public Task<bool> ExisteParaParejaAsync(Guid l, Guid p, Guid? e = null, CancellationToken t = default) => Task.FromResult(false); public Task GuardarAsync(CancellationToken t = default) => Task.CompletedTask; public Task EliminarAsync(Oferta x, CancellationToken t = default) => Task.CompletedTask; }
}
