@host = http://localhost:5018

# Registrar proveedor
POST {{host}}/api/v1/proveedores
Content-Type: application/json
Accept: application/json

{
  "nombre": "Empresa Central"
}

###

# Crear licitación en Borrador
# @name crearLicitacion
POST {{host}}/api/v1/licitaciones
Content-Type: application/json
Accept: application/json

{
  "codigo": "LIC-2030-001",
  "titulo": "Compra de equipo informático",
  "presupuestoEstimadoCrc": 1250000.50,
  "fechaCierre": "2030-10-15T18:30:00-06:00"
}

###

# Publicar el Borrador creado por la solicitud anterior
POST {{host}}/api/v1/licitaciones/{{crearLicitacion.response.body.$.id}}/publicar
Accept: application/json

###

# Consultar OpenAPI en Development
GET {{host}}/openapi/v1.json
Accept: application/json

###
